### PR TITLE
Major refactoring: add multiroom support, new creep spawner, and more.

### LINKED ISSUE #14: Refactor code based on rooms
Reference: https://github.com/ErikVanNorstrand/screeps-typescript

Right now the way we implement everything relies on us having only one room only. So we need to refactor so that everything's not room-dependent.

Trying to fix this may also help us in fixing #7.

### PR DESCRIPTION
**Pull request by resir014**
Fixes #14 and #7.

This contains all of the refactoring efforts that were made to improve the creep spawning logic, making our code support mutiple rooms, and a lot more.
## Progress
- [x] Refactor every class for mutiroom support
- [x] Fix issues with `MemoryManager`
- [x] New creep spawner
- [x] Code cleanups
- [x] Update keywords & coding style to ES6 standards (e.g. `var` to `let` or `const`)

### CODE REVIEW

**Comment by resir014** [comment]
It seems like this will terribly break `MemoryManager`, since we don't have it set up for multi-room yet. Every time a creep gets deleted, the `MemoryManager` class shits the bed since we have deleted the memory but for some reason `CreepManager` still lists the creep even after said creep memory got deleted, so everything breaks.

image

Refactoring `MemoryManager` for multi-room support, or figuring out a better way to update a creep's memory state would be our top priority at this time.

**Comment by ChaoticWeg** [comment]
It looks like this issue has been fixed (see issue #16). Let me know how it passes testing on your end.

**Comment by resir014** [comment]
I tried using the code for my room, and everything seems to be fixed on my end.

**Comment by resir014** [comment]
By now consider most of the rough edges fixed. I'll now move towards migrating most of the keywords/styles to ES6 standards.

**Comment by resir014** [comment]
ES6-ifying done. Creep spawner featuring `JobManager` coming right up.

**Comment by resir014** [comment]
And consider the cleanup of the code complete. Passing over to @ChaoticWeg for tests & creep spawning tweaks.

**Comment by ChaoticWeg** [comment]
Looks to me like all tests are passing and this PR is ready to merge. I haven't done creep spawning yet, I'm in and out of the house at the moment.

@resir014: If you're ready to merge this PR, go ahead, and I'll tweak creep spawning once we're done with convergence.

**Comment by resir014** [comment]
Cool! Merging this then.

**Pull request merged**
